
BEGIN

	DELETE FROM departments WHERE department_id = 300;

	IF(SQL%ROWCOUNT > 0) THEN
		DBMS_OUTPUT.PUT_LINE('LINHAS AFECTADAS:' || SQL%ROWCOUNT);
	ELSE
		DBMS_OUTPUT.PUT_LINE('NENHUMA LINHA AFECTADA');
	END IF; 

END;